### ISSUE TITLE
Errors on old filter: alpha() function

### ISSUE THREAD

**Issue by danny-andrews** [csstools/postcss-env-function#10]
I'm getting an error when trying to run postcss-env-fn on some code which uses the old syntax for applying opacity (`filter: alpha(opacity=23)`).

Code:
```css
.className {
  filter: alpha(opacity=45);
}
```

Error message:
```
CssSyntaxError: postcss-env-fn: <css input>:1:1: Unknown word
```
