### ISSUE TITLE
Generating fallback declaration for safe-area env variables for older browsers

### ISSUE THREAD

**Issue by stof** [csstools/postcss-env-function#6]
Browsers supporting the `env` function must support the 4 `safe-area-inset-*` variables as user-agent env variables (with a value of 0 if they don't need as specific safe area).
But using it in a declaration (for instance to add some margin or padding taking it into account) won't work for older browsers (they will consider the rule as invalid and drop it). This means we need fallback declarations for older browsers:

```css
/* future CSS */
.container {
    padding-left: calc(10px + env(safe-area-inset-left));
}

/* cross-browser CSS */
.container {
    padding-left: calc(10px + 0); /* For older browsers */
    padding-left: calc(10px + constant(safe-area-inset-left)); /* For Safari 11.0 */
    padding-left: calc(10px + env(safe-area-inset-left));
}
```

Browser compatibility: https://developer.mozilla.org/en-US/docs/Web/CSS/env#Browser_compatibility

In that case, the old browser fallback could even be written as `10px` but that could be left to a separate optimizer plugin.

Is this plugin able to handle that ? And if no, is there any plan to support it (or is there any other postcss plugin doing that, that I failed to find) ?
