### ISSUE TITLE
Is it possible to assign env variable to scss variable?

### ISSUE THREAD

**Issue by asolopovas** [csstools/postcss-env-function#7]
Hi, 

I am using wordpress and often I need to use `$theme-path` across my project to specify the location of assets. I was able to pass the necessary var using your tool into the css file but it only works if I apply this way `background: url(env(--theme-path) + '/images/img.jpg')` if I try to do something like that
```scss
$theme-path: env(--theme-path)
.el {
    background: url($theme-path + "/static/img/background.png");
}
```
it throws an error. Is there a way around it?
